### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by mtoko** [paulhayes/node-red-contrib-usb-hid-relay#2] opened 2019-08-20 09:21 UTC
Hi
I have tried to install through the pallette manager and get the following error
rebuild-install WARN install No prebuilt binaries found (target=10.16.0 runtime=node arch=arm libc= platform=linux)
make: Entering directory '/home/pi/.node-red/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.

This is on a Raspberry Pi 3b+ with Raspian Buster

**Comment by paulhayes** [comment] 2019-08-21 21:44
Hi mtoko, I haven't tried this on a linux distro yet. I have a few raspberry pi's lying about. I'll find time and give it a try. 

However the good news is that it looks like there's a simple fix for this specific problem. The issue is caused by a missing library, and easily resolved, following the instructions here:

https://github.com/node-hid/node-hid/pull/253

Let me know how you get on.

**Comment by paulhayes** [comment] 2019-08-21 21:49
I've just released a patch 0.2.1, so do an npm update for this module too

**Comment by mtoko** [comment] 2019-08-22 08:32
Hi Thanks for the response. I have added the library now get this error


pi@DinPi:~/.node-red $ npm install node-red-contrib-usb-hid-relay
The authenticity of host 'github.com (140.82.118.4)' can't be established.ontri
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? [..................] \ fe                                    [..................] \ fetchMetadata: sill resolveWithNewModule node-red-contrib-usb-hid-relay@0.2.1 checking insta
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/josephdadams/USBRelay.git
npm ERR!
npm ERR! Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by paulhayes** [comment] 2019-08-22 10:07
Sorry, you probably don't have ssh set up properly. I've republished with the dependency using https instead. Try now.

**Comment by paulhayes** [comment] 2019-09-01 12:32
Hi @mtoko did you have any luck?

**Comment by mtoko** [comment] 2019-09-01 12:46
Hi
I did try again after 0.2.2 but it seems there is a build issue see log file here
https://pastebin.com/dibcZA4C

Have you tested this on Raspberry Pi? I would think this would be a frequent use case.
Thanks

**Comment by paulhayes** [comment] 2019-09-01 21:12
I'll investigate tomorrow. Thanks for the error log.

**Comment by paulhayes** [comment] 2019-09-09 17:42
Hi there, I managed to get it to install on raspbian. I've updated the documentation to help others with this. You need to install the following:

```sudo apt-get install libudev-dev librtlsdr-dev libusb-1.0-0-dev libpthread-stubs0-dev git```

**Closed as completed** 2019-09-09 17:44 UTC

**Comment by paulhayes** [comment] 2019-09-09 18:14
Please be aware that the package is still not working for raspberry pi, I'm working to fix it, it's a different issue, so I've opened a new issue ticket.

**Comment by Hitower78** [comment] 2020-04-03 10:01
Hi
is this solved?
I try an installation, but it failed (see NodeRed Node section)
NodeRede Raspberry 1

On a Windows system i should run, because i can install that node
But there is a warn: 
[usb ralay Registered invalid property name 'usbhiddelayconnectioncheckinterval' Properties for this node must start with 'usbrelay'


Thanks

**Comment by paulhayes** [comment] 2020-04-04 23:18
This is not solved. But now I'm in isolation I really have no excuse. Thanks for the reminder about the windows warning, this was fixed but I had forgot to publish the latest version to npm. That's now done, so a simple update should remove that.

> Hi
> is this solved?
> I try an installation, but it failed (see NodeRed Node section)
> NodeRede Raspberry 1
> 
> On a Windows system i should run, because i can install that node
> But there is a warn:
> [usb ralay Registered invalid property name 'usbhiddelayconnectioncheckinterval' Properties for this node must start with 'usbrelay'
> 
> Thanks

**Comment by Hitower78** [comment] 2020-04-06 15:45
Thanks!
i update my Version but on this Notebook (XPS15) the Relaisboard doesnt show up in the settings.
i check it with my testtool a gui to "CommandApp_USBRelay.exe" and Node-Red
i have to install node-red on a different PC, but i am in Homeoffice and this will take a while...

Greetings from Hamburg
Daniel
